spring.application.name=notification-service

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=d910b4d14c703b
spring.mail.password=0de83da1f143e6
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

rabbit.trx.key.ussd=key.ussd
rabbit.trx.key.new=new
rabbit.trx.key.log=log
rabbit.auth.change.password=password